routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('role', 'RoleController');
Route::resource('permission', 'PermissionController');
Route::resource('user', 'UserController');

app/Permission.php
<?php

namespace App;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission {
    
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;

class PermissionController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $link_active = 'permission';
        $permission = Permission::all();
        return view('permission.index', compact('permission'), compact('link_active'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $link_active = 'permission';
        return view('permission.create', compact('link_active'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'name' => 'required'
        ]);
        $permission = new Permission;
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
        $message = message('Successfully Added Permission', 'success');
        session()->flash('message', $message);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $link_active = 'role';
        $permission = Permission::find($id);
        return view('permission.edit', compact(['link_active', 'permission']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $this->validate($request, [
            'name' => 'required'
        ]);
        $permission = Permission::find($id);
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
         $message = message('Successfully Updated Permission', 'success');
        session()->flash('message', $message);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/permission/create.blade.php
@extends('layouts.admin_master')

@section('content')
<div class="box box-primary">
    <form action="{{route('permission.store')}}" method="post">
  @csrf

        <div class="box-header with-border">
            <h3 class="box-title"><a href="{{route('permission.index')}}" class="btn btn-success"><i class="fa fa-eye"></i>&nbsp;View Permission</a></h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group">
                        <label for="name">Permission Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Permission Name">
                    </div>
                    <div class="form-group">
                        <label for="name">Display Name</label>
                        <input type="text" class="form-control" name="display_name" id="display_name" placeholder="Display Name">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" id="description" rows="3" placeholder="Enter Description..."></textarea>
                    </div>

                </div>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>



@endsection

resources/views/permission/edit.blade.php
@extends('layouts.admin_master')

@section('content')
<div class="box box-primary">
    <form action="{{route('permission.update',$permission->id)}}" method="post">
  @csrf
<input name="_method" type="hidden" value="PUT">
        <div class="box-header with-border">
            <h3 class="box-title"><a href="{{route('permission.index')}}" class="btn btn-success"><i class="fa fa-eye"></i>&nbsp;View Permission</a></h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group">
                        <label for="name">Permission Name</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{$permission->name}}">
                    </div>
                    <div class="form-group">
                        <label for="name">Display Name</label>
                        <input type="text" class="form-control" name="display_name" id="display_name" value="{{$permission->display_name}}">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" id="description" rows="3">{{$permission->description}}</textarea>
                    </div>

                </div>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>



@endsection

resources/views/permission/index.blade.php
@extends('layouts.admin_master')

@section('content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title"><a href="{{route('permission.create')}}" class="btn btn-success"><i class="fa fa-plus-square-o" aria-hidden="true"></i>&nbsp;Create Permission</a></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                ?>
                @foreach($permission as $value)
                <tr>
                    <td>{{$i++}}</td>
                    <td>
                        {{$value->name}}
                    </td>
                    <td> {{$value->display_name}}</td>
                    <td> {{$value->description}}</td>
                    <td>  
                       <a href="{{route('permission.edit',$value->id)}}"  class="btn btn-primary">Edit</a>
                        <button type="button"  class="btn btn-danger">Delete</button>

                    </td>
                </tr>
                @endforeach


            </tbody>
            <tfoot>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.box-body -->
</div>
@endsection