routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('role', 'RoleController');
Route::resource('permission', 'PermissionController');
Route::resource('user', 'UserController');

app/Role.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole {
    
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\Permission;

class RoleController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $link_active = 'role';
        $role = Role::all();
        return view('role.index', compact('role'), compact('link_active'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $link_active = 'role';
        $permission = Permission::all();
        return view('role.create', compact('link_active'), compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        // dd($request->all());
        $this->validate($request, [
            'name' => 'required'
        ]);
        $role = new Role;
        $role->name = $request->name;
        $role->display_name = $request->display_name;
        $role->description = $request->description;
        $role->save();

        foreach ($request->permission as $key => $value) {
            $role->attachPermission($value);
        }

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $link_active = 'role';
        $role = Role::find($id);
        $permission = Permission::all();
        $role_permissions = $role->perms()->pluck('id','id')->toArray();
         dd($role_permissions);

        return view('role.edit', compact(['link_active','permission','role','role_permissions']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/role/create.blade.php
@extends('layouts.admin_master')

@section('content')
<div class="box box-primary">
    <form action="{{route('role.store')}}" method="post">
        @csrf

        <div class="box-header with-border">
            <h3 class="box-title"><a href="{{route('role.index')}}" class="btn btn-success"><i class="fa fa-eye"></i>&nbsp;View Role</a></h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group">
                        <label for="name">Role Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Role Name">
                    </div>
                    <div class="form-group">
                        <label for="name">Display Name</label>
                        <input type="text" class="form-control" name="display_name" id="display_name" placeholder="Display Name">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" id="description" rows="3" placeholder="Enter Description..."></textarea>
                    </div>
                    <div class="form-group">
                        <h3>Permission List</h3>
                        @foreach($permission as $value)
                        <label>
                            <input type="checkbox" value="{{$value->id}}" name="permission[]" class="minimal">
                          {{$value->name}}
                        </label><br>
                        @endforeach
                    </div>
                </div>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" value="Submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>



@endsection

resources/views/role/edit.blade.php
@extends('layouts.admin_master')
<?php
//     dd($role);
?>
@section('content')
<div class="box box-primary">
    <form action="{{route('role.update',$role->id)}}" method="post">
        @csrf
        <input name="_method" type="hidden" value="PUT">
        <div class="box-header with-border">
            <h3 class="box-title"><a href="{{route('role.index')}}" class="btn btn-success"><i class="fa fa-eye"></i>&nbsp;View Role</a></h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group">
                        <label for="name">Role Name</label>
                        <input type="text" value="{{$role->name}}" class="form-control" name="name" id="name" placeholder="Role Name">
                    </div>
                    <div class="form-group">
                        <label for="name">Display Name</label>
                        <input type="text" value="{{$role->display_name}}" class="form-control" name="display_name" id="display_name" placeholder="Display Name">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" id="description" rows="3" placeholder="Enter Description...">{{$role->description}}</textarea>
                    </div>
                    <div class="form-group">
                        <h3>Permission List</h3>
                        @foreach($permission as $value)
                        <label>
                            <input type="checkbox" {{in_array($value->id,$role_permissions)?"checked":""}}  name="permission[]" value="{{$value->id}}" class="minimal">
                            {{$value->name}}
                        </label><br>
                        @endforeach
                    </div>
                </div>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" value="Submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>



@endsection

resources/views/role/index.blade.php
@extends('layouts.admin_master')

@section('content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title"><a href="{{route('role.create')}}" class="btn btn-success"><i class="fa fa-plus-square-o" aria-hidden="true"></i>&nbsp;Create Role</a></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                ?>
                @foreach($role as $value)
                <tr>
                    <td>{{$i++}}</td>
                    <td>
                        {{$value->name}}
                    </td>
                    <td> {{$value->display_name}}</td>
                    <td> {{$value->description}}</td>
                    <td>  
                        <a href="{{route('role.edit',$value->id)}}"  class="btn btn-primary">Edit</a>
                        <button type="button"  class="btn btn-danger">Delete</button>

                    </td>
                </tr>
                @endforeach



            </tbody>
            <tfoot>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.box-body -->
</div>
@endsection